{
    "source file": "test_seq_dataset.py",
    "line number": "140",
    "func name": "test_buffer_dtype_mismatch_error",
    "func arg": "()",
    "comments": ""
}