{
    "source file": "test_op.py",
    "line number": "384",
    "func name": "test_debug_error_message",
    "func arg": "()",
    "comments": ""
}