{
    "source file": "test_annotations1.py",
    "line number": "50",
    "func name": "test_dict_instantiation_graph_obj_error_2",
    "func arg": "()",
    "comments": ""
}